apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecommerce-dev-postgre-db-credentials
  # namespace: dev
  labels:
    env: dev
    managed-by: terraform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ecommerce-dev-postgre-db-credentials        # K8s Secret name
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: /ecommerce/dev/postgre-db-credentials    # AWS Secret name
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /ecommerce/dev/postgre-db-credentials
        property: password
