apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.database | quote }}  # shopverse-dev-rds-mysql
  # namespace: ecommerce-dev
spec:
  type: ExternalName
  externalName: "<your-db.cluster-abcdefghijkl.ap-south-1.rds.amazonaws.com>"
