name: Reusable - GO PR Check (No Docker)
on:
  workflow_call:
    inputs:
      service-name:
        description: "Service name (e.g. api-gateway)"
        required: true
        type: string

      gitleaks:
        description: "Gitleaks Scan"
        required: true
        type: boolean
        default: false

      sonarqube-scan:
        description: "SonarQube Scan"
        required: true
        type: boolean
        default: false

permissions:
  contents: read              # Checkout
  # pull-requests: read         # Read Pull Requests
  # security-events: write      # Upload SARIF (Gitleaks, Trivy, CodeQL)
  # actions: read               # Required by CodeQL action

jobs:    

  Gitleaks-Job:
    name: Gitleaks Scan
    if: ${{ inputs.gitleaks }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v3
        # continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Uncomment if your organization requires a Gitleaks license
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Upload Gitleaks SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
          category: gitleaks-${{ inputs.service-name }}--${{ github.run_number }}
      
      - name: Upload Gitleaks report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-sarif-${{ github.run_number }}--${{ github.run_number }}
          path: results.sarif
          if-no-files-found: warn
          retention-days: 1

  Sast-Sonarqube-Job:
    name: Sast Sonarqube
    if: ${{ inputs.sonarqube-scan }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.service-name }}

    permissions:
      contents: read
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      # - name: Update go.sum
      #   run: go mod tidy

      - name: Download dependencies
        run: go mod download
          
      - name: Run Go tests
        run: go test -coverprofile=coverage.out ./...

      - name: Verify coverage report
        run: |
          test -f coverage.out || {
            echo "ERROR: coverage.out not found"
            exit 1
          }

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  Trivy-Fs-Scan-Job:
    name: Trivy FS Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          version: v0.72.0
          scan-type: fs
          scan-ref: ${{ inputs.service-name }}
          format: sarif
          output: trivy-fs-${{ github.run_number }}.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0   # 1

      - name: Upload Trivy SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-fs-${{ github.run_number }}.sarif
          category: trivy-fs-${{ inputs.service-name }}

  Codeql-Analysis-Job:
    name: CodeQL 
    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash
        working-directory: ./backend

    permissions:
      contents: read  
      security-events: write
      actions: read

    steps:
      # Checkout Source Code
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Create CodeQL configuration
        run: |
          cat > codeql-config.yml <<EOF
          name: Go CodeQL
          paths:
            - ${{ inputs.service-name }}
          EOF

      # Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: go
          queries: security-extended
          build-mode: manual
          config-file: codeql-config.yml
          
      # Build GO Application automatically
      # - name: Autobuild 
      #   uses: github/codeql-action/autobuild@v4

      # Download Go dependencies
      - name: Download Go dependencies
        working-directory: ${{ inputs.service-name }}
        run: go mod download
        
      # Build Go Application
      - name: Build Go App manually
        working-directory: ${{ inputs.service-name }}
        run: go build ./...
          
      # Run CodeQL analysis 
      - name: Perform CodeQL Analysis 
        uses: github/codeql-action/analyze@v4 
        with: 
          category: "/language:go"
