name: CICD - GO Services 

on:
  push:
    branches: [develop, 'release/**']
      
  paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

# permissions:
#   contents: read
#   pull-requests: read
#   security-events: write
#   actions: read
#   id-token: write

jobs:

  backend:
    name: Backend Security Pipeline
    uses: ./.github/workflows/_go-build.yml
    with:
      service-name: backend
      gitleaks: true
      sonarqube-scan: true
      ecr-repository: shopverse/backend
      aws-region: us-east-1

    permissions:
      contents: read
      pull-requests: read
      security-events: write
      actions: read
      id-token: write

    secrets: inherit
