apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.externalNameService | quote }}  
  # namespace: shopverse-dev
spec:
  type: ExternalName
  externalName: {{ .Values.mysql.host | quote }}
