apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backend.ingress.name }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: {{ .Values.backend.ingress.path }}  # /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.service.name }}
                port:
                  number: 8080
