apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: shopverse
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}             # 8080
      targetPort: {{ .Values.service.targetPort }} # 8080
      protocol: TCP
  selector:
    app: shopverse
    component: backend
