{{- if .Values.backendIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backendIngress.name }}                             # shopverse-backend-ingress
  {{- with .Values.backendIngress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.backendIngress.ingressClassName }}     # alb
  rules:
    - http:
        paths:
          - path: {{ .Values.backendIngress.path }}                   # /api
            pathType: {{ .Values.backendIngress.pathType }}           # Prefix
            backend:
              service:
                name: {{ .Values.backendIngress.service.name }}
                port:
                  number: {{ .Values.backendIngress.service.port }}           # 8080
{{- end }}
