apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: shopverse
    component: frontend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: shopverse
      component: frontend
  template:
    metadata:
      labels:
        app: shopverse
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ include "shopverse.frontend.image" . }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
