apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.ingress.name }}      # shopverse-frontend-ingress
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}     
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: {{ .Values.frontend.ingress.path }}  # /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.service.name }}
                port:
                  number: {{ .Values.frontend.service.port }}  # 8080
