apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopverse-frontend-ingress
  annotations:
    # frontend-specific health check
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port

    # This is important to mix all the service ingresses and form one complete ingress
    alb.ingress.kubernetes.io/group.name: shopverse-dev

    alb.ingress.kubernetes.io/group.order: "2"   # lower priority

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopverse-frontend-svc
                port:
                  number: 8080
