apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: shopverse
    component: frontend
spec:
  #type: NodePort
  ports:
    - port: {{ .Values.service.port }}     # 8080
      targetPort: {{ .Values.service.targetPort }} # 8080
      protocol: TCP
  selector:
    app: shopverse
    component: frontend
