# ──────────────────────────────────────
# Frontend
# ──────────────────────────────────────
frontend:
  deploymentName: shopverse-frontend
  replicas: 2
  image: ""  # frontend-image
  serviceName: shopverse-frontend-svc
  servicePort: 80
  ingressName: shopverse-frontend-ingress
  ingressHost: ""

# ──────────────────────────────────────
# Backend
# ──────────────────────────────────────
backend:
  deploymentName: shopverse-backend
  replicas: 2
  image: ""  # backend-image
  serviceName: shopverse-backend-svc
  servicePort: 8080
  ingressName: shopverse-backend-ingress
  ingressHost: ""

# ──────────────────────────────────────
# MySQL
# ──────────────────────────────────────
mysql:
  external-name-service: shopverse-mysql
  database: shopverse
  user: shopverse
    
# ──────────────────────────────────────
# Shared
# ──────────────────────────────────────
ingress:
  enabled: false
  ingressClassName: alb
  annotations: {}

jwtSecret: ""
