apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.externalNameService | quote }}  
  # namespace: shopverse-dev
spec:
  type: ExternalName
  externalName: "<your-db.cluster-abcdefghijkl.ap-south-1.rds.amazonaws.com>"
