name: Reusable — GO PR Check (no Docker)

on:
  workflow_call:
    inputs:
      service-name:
        description: "Service Name"
        required: true
        type: string

      runner:
        description: "Runner label"
        required: false
        type: string
        default: ubuntu-latest

      sonarqube-scan:
        description: "Enable SonarQube Scan"
        required: true
        type: boolean
        default: false

      sonar-host-url:
        description: "Sonarqube Host Url"
        required: true
        type: string
        default: ""

      gitleaks-scan:
        description: "Enable Gitleaks Scan"
        required: true
        type: boolean
        default: false

      trivy-fs-scan:
        description: "Enable Trivy FS Scan"
        required: true
        type: boolean
        default: false

      codeql-scan:
        description: "Enable Codeql Scan"
        required: true
        type: boolean
        default: false
        

    secrets:
      SONAR_TOKEN:
        required: false    
  
jobs:
  
  Gitleaks-Job:
    if: ${{ inputs.gitleaks-scan }}
    name: Gitleaks
    uses: ./.github/workflows/reusable-gitleaks.yml
    with:
      service-name: ${{ inputs.service-name }} 
      runner: ${{ inputs.runner }}
    # secrets: inherit

  Sonarqube-Job:
    if: ${{ inputs.sonarqube-scan }}
    name: Sonarqube
    uses: ./.github/workflows/reusable-sonarqube.yml
    with:
      service-name: ${{ inputs.service-name }} 
      runner: ${{ inputs.runner }}
      sonar-host-url: ${{ inputs.sonar-host-url }}
            
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Trivy-Fs-Scan-Job:
    if: ${{ inputs.trivy-fs-scan }}
    name: Trivy Fs Scan
    uses: ./.github/workflows/reusable-trivy-fs.yml
    with:
      service-name: ${{ inputs.service-name }}
      runner: ${{ inputs.runner }}

  Codeql-Analysis-Job:
    if: ${{ inputs.codeql-scan }}
    name: Codeql Analysis
    uses: ./.github/workflows/reusable-codeql.yml
    with:
      service-name: ${{ inputs.service-name }}
      runner: ${{ inputs.runner }}
