name: Reusable - Sonarqube

on:
  workflow_call:
    inputs:
      service-name:
        description: "Service Name"
        required: true
        type: string
      
      sonar-host-url:
        description: "Sonar Host Url"
        required: true
        type: string

      runner:
        description: "Runner label"
        required: false
        type: string
        default: ubuntu-latest
    
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  Sonarqube:
    name: Sast Sonarqube
    runs-on: ${{ inputs.runner }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.service-name }}

    permissions:
      contents: read
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      # - name: Update go.sum
      #   run: go mod tidy

      - name: Download dependencies
        run: go mod download
          
      - name: Run Go tests
        run: go test -coverprofile=coverage.out ./...

      - name: Verify coverage report
        run: |
          test -f coverage.out || {
            echo "ERROR: coverage.out not found"
            exit 1
          }

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
